export const GET_BOOKS = 'GET_BOOKS';
export const ADD_BOOK = 'ADD_BOOK';
export const UPLOAD_BOOKS = 'UPLOAD_BOOKS';
export const DELETE_BOOK = 'DELETE_BOOK';
export const UPDATE_BOOK = 'UPDATE_BOOK' ;
export const SEARCH_BOOKS_BY_TITLE = 'SEARCH_BOOKS_BY_TITLE';
export const SEARCH_BOOKS_BY_AUTHOR = 'SEARCH_BOOKS_BY_AUTHOR';
export const BOOKS_LOADING = 'ITEMS_BOOKS';
